version: "3.8"

services:
  db:
    image: postgres:15
    container_name: db_postgres_intuitivecare
    restart: always
    environment:
      POSTGRES_USER: teste3
      POSTGRES_PASSWORD: test3intuitivecare
      POSTGRES_DB: demonstracoes_contabeis
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
    driver: local